server:
  port: 8080 # Puerto público del Gateway

spring:
  application:
    name: api-gateway

  # Configuración de Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          # ¡Exactamente la misma URL que en servicio-gestion!
          # Apunta a la URL que Postman usa para pedir el token.
          issuer-uri: http://keycloak:8180/realms/tpi-logistica
